spring:
 profiles.active: heroku

---
spring:
 profiles: development
 jpa:
     hibernate:
       ddlAuto: create-drop
#        use the EJB3NamingStrategy, which doesn't convert camelCase to snake_case, but keeps it as it is
       namingStrategy: org.hibernate.cfg.EJB3NamingStrategy
     show-sql: false
datasource:
 StudyBuddydb:
     url: jdbc:postgresql://localhost:5432/StudyBuddydb
     username: postgres
     password: postgres

---

spring:
 profiles: heroku
 jpa:
   hibernate:
     ddlAuto: create
     namingStrategy: org.hibernate.cfg.EJB3NamingStrategy
   show-sql: false
datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
# d5aug8a8mir0gb:
#     url: jdbc:postgres://ec2-54-235-120-39.compute-1.amazonaws.com:5432/d5aug8a8mir0gb
#     username: wfruzffpoteugr
#     password: 5ed4d41bd566adcbcc0bab767a45e9bfc9f9d6447bef0b5a59da25d008845530



---

spring:
 profiles: production
datasource:
 StudyBuddydb:
      url: jdbc:postgresql://localhost:5432/StudyBuddydb
      username: postgres
      password: postgres

---