version: 2

jobs:
  build:
    working_directory: ~/circulate
    docker:
      - image: openjdk:7
        environment:
          FLASK_CONFIG: testing
          TEST_DATABASE_URL: postgresql://ubuntu@localhost/circle_test?sslmode=disable
      - image: postgres:9.6.2
          environment:
            POSTGRES_USER: ubuntu
            POSTGRES_DB: circle_test
            POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - run: echo "Juan Carlos"